[package]
name = 'WoolfRiskyGame'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.Woolf]
local = "../Woolf"

[addresses]
#woolf_deployer = "_"
woolf_risky_gamer = "_"