[package]
name = "WoolfResourceAccount"
version = "0.0.1"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
woolf_deployer = "_"
